modLoader="javafml"
loaderVersion="${mod_loader_version}"
license="GPL"
# issueTrackerURL=""
# displayURL=""
logoFile="icon.png"
credits="Sonic Ether, vlad2305m"
authors="Sonic Ether, vlad2305m, Max Henkel"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/sound_physics_remastered.json"
description='''Provides realistic sound attenuation, reverberation, and absorption through blocks.'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cloth_config"
    mandatory=false
    versionRange="[${cloth_config_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="voicechat"
    mandatory=false
    versionRange="[${minecraft_version}-2.0.0,)"
    ordering="AFTER"
    side="BOTH"